#!/bin/sh

# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/


# try to run the IP tables executable. We can't just run it, because then it 
# won't try to talk to the kernel module. Instead, run it with the -L command.
# For performance reasons, list only one chain, known to exist
iptables -L INPUT 2>/dev/null >/dev/null || {
  echo "quit" >&3
  exit 1
}

# same thing for ip6
ip6tables -L INPUT 2>/dev/null >/dev/null || {
  echo "quit" >&3
  exit 1
}

echo "quit" >&3
exit 0
