#!/bin/bash
# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/
SCRIPT_NAME="/etc/openpanel/rc.firewall"

if [ -f $SCRIPT_NAME ]; then
	exec $SCRIPT_NAME
else
	echo "No IpTables configuration script found"
	exit 1
fi
