#!/bin/bash
# This file is part of OpenPanel - The Open Source Control Panel
# OpenPanel is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
#
# Please note that use of the OpenPanel trademark may be subject to additional 
# restrictions. For more information, please visit the Legal Information 
# section of the OpenPanel website on http://www.openpanel.com/
SCRIPT_NAME="/etc/openpanel/rc.firewall"

if [ -f $SCRIPT_NAME ]; then
	$SCRIPT_NAME || exit 1
	
	# optional: Implied SNAT
	
	if [ -e /etc/openpanel/iptables.nat-gateway ]; then
	  snat_device=$(cat /etc/openpanel/iptables.nat-gateway)
	  if [ -z "$snat_device" ]; then
	    snat_device=eth0
	  fi
	  
	  extip=$(ip -f inet addr list dev $snat_device | grep inet | head -1 | sed -e "s/.*inet //;s@/.*@@")
	  
	  /sbin/iptables -t nat -A POSTROUTING -o $snat_device -j SNAT --to $extip
	fi
	
	/etc/init.d/iptables save
else
	echo "No IpTables configuration script found"
	exit 1
fi
